---
- name: Install Docker
  hosts: aws
  become: True

  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: True

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker Engine, containerd, and Docker Compose
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
          - docker-compose-plugin
        force_apt_get: yes
        state: present
        update_cache: True

    - name: Ensure group "docker" exists with correct gid
      group:
        name: docker
        state: present
    
    - name: Add the current user to the docker group
      user:
        name: "ubuntu"
        groups: docker
        append: yes

