---
- name: Install VS code
  hosts: localhost
  become: yes
  tasks:
    - name: install vscode
      apt:
        deb: https://az764295.vo.msecnd.net/stable/1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a/code_1.74.1-1671015296_amd64.deb
